path: C:\Users\gauti\Projets\port-fauna-detector\data\inaturalist
train: images/train
val: images/val
names:
  0: poisson
  1: dorade_royale
  2: bar_europeen
  3: mulet
  4: sar_commun
  5: girelle
  6: rascasse
  7: congre
  8: murene
  9: saupe
  10: blennie
  11: gobie
  12: hippocampe
  13: castagnole
  14: oblade
  15: bogue
  16: sar_museau_noir
  17: sparaillon
  18: serran_chevrette
  19: serran_ecriture
  20: atherine
  21: rouget
  22: chinchard
  23: vive
  24: sole
  25: oursin_violet
  26: oursin_noir
